### ISSUE TITLE
Activating extension 'SolomonRosemite.lsp-todo' failed: Cannot find module 'multilang-extract-comments'

### ISSUE THREAD

**Issue by rollecode** [SolomonRosemite/TypeScript-Todo#11]
Version 1.8.6 doesn't work at all for me right now.
Just updated the plugin after starting VSCode.

```
Activating extension 'SolomonRosemite.lsp-todo' failed: Cannot find module 'multilang-extract-comments'
Require stack:
- /Users/rolle/.vscode/extensions/solomonrosemite.lsp-todo-1.8.6/client/out/language.js
- /Users/rolle/.vscode/extensions/solomonrosemite.lsp-todo-1.8.6/client/out/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js.
```

**Comment by solomonrosemite** [comment]
Indeed version 1.8.6 had a issue when publishing. There is a version 1.8.7 out now, perhaps that will fix your issue.

**Comment by rollecode** [comment]
Still nothing.

![Screen-Shot-2022-09-28-17-45-33 36](https://user-images.githubusercontent.com/1534150/192810069-c0ae554d-3588-4e13-b4fd-cf3ee1045bdc.png)

![Screen-Shot-2022-09-28-17-45-36 19](https://user-images.githubusercontent.com/1534150/192810107-a1d22e5f-502d-4d26-98ad-9a4d4f75044a.png)

**Comment by solomonrosemite** [comment]
Damn. I created another hotfix v1.8.8 which should hopefully work. I tested it on a test Linux and Windows machine.
Let me know if the new version solved your Problem.

**Comment by rollecode** [comment]
Seems to work now, thanks!
