### ISSUE TITLE
Freedom to choose words which to consider as todo

### ISSUE THREAD

**Issue by rollecode** [SolomonRosemite/TypeScript-Todo#12]
Right now getting all kinds of fix-comments as announced. For example this is just a comment that it has been fixed and should not be highlighted:

![Screen-Shot-2022-09-29-11-36-09 86](https://user-images.githubusercontent.com/1534150/192983316-1868ec5a-845e-4a02-9a56-0926a08b8a7b.png)

Can we have a setting for which words should be considered as todo highlight? You could set it up like this in settings.json:

```json
{
    "simpleTodo.overrideTodoWords": [
      "TODO",
      "Bug",
      "Something"
    ]
  }

**Comment by solomonrosemite** [comment]
Sure, the version 1.9.0 now supports this feature and looks like so:
```jsonc
"simpleTodo.overrideActionKeywords": [
    {
      "actionName": "Todo:",
      "severity": "Information"
    },
    {
      "actionName": "Bug:",
      "severity": "Warning"
    },
    {
      "actionName": "Fix:",
      "severity": "Information"
    },
    {
      "actionName": "Note:",
      "severity": "Hint"
    }
]
```
Keep in mind that the actions names and severity levels are not case sensitive.
Let me know if you have any questions or facing any issues.

**Comment by rollecode** [comment]
Very nice! It works! This is one of the best extensions for VSCode. Thank you so much & keep up the good work! ❤️

**Comment by solomonrosemite** [comment]
Thanks, always glad to help.
