### ISSUE TITLE
Not showing

### ISSUE THREAD

**Issue by TheRealArtonn** [SolomonRosemite/TypeScript-Todo#2]
Installed the plugin, but not showing up in visual studio.-

**Comment by solomonrosemite** [comment]
Hey TheRealArtonn,
Thanks for sharing your issue.

There are a few things I need to know to solve your issue:

- What was the programming language it failed to showing up?
- Please send a screenshot or a code snippet where it failed to showing up.

Do these things and let me know how that worked out:
1. Reinstall the Visual Studio Code Simple-Todo extension.
2. Open Visual Studio Code and create a file named `app.js`
3. Paste this line of code in the `app.js` file. `// Todo: Simple Test` 

It should look something like this...
![](https://user-images.githubusercontent.com/60587271/111963477-dcbd1f80-8af3-11eb-9149-30b58e8e1ed7.PNG)

Let me know if that worked. If it doesn't it would be great if you could send me a image of the `app.js`.

**Comment by solomonrosemite** [comment]
Closing this issue for now, due to lack of response. Feel free to comment on this issue if you are facing any similar problems.
