### ISSUE TITLE
Allow excluding files/folders

### ISSUE THREAD

**Issue by rollecode** [SolomonRosemite/TypeScript-Todo#9]
Currently the plugin searches from hundreds of files inside folders like vendor, dist, prod, etc... Please allow excluding folders in settings.json.

I have currently modified the plugin code manually in my `$HOME/.vscode/extensions/solomonrosemite.lsp-todo-1.5.6/client/out/extension.js` file, which is in src:

https://github.com/SolomonRosemite/TypeScript-Todo/blob/de8e95f6e888b80e74b94f6c6b7dcf00fda587b8/todo-list/client/src/extension.ts#L59

to:

```js
.findFiles("**/*.{ts,js,html,bat,c,cpp,cs,go,java,lua,php,yaml,py,swift,dart,powershell}", "**/{Library,plugins,mu-plugins,vendor,wp,dev,prod,node_modules,dist,build,.next}/**")
```

**Comment by solomonrosemite** [comment]
Thanks for pointing that out.
I made a few changes and now you should be able to override folders and files exclusions.

When updating to v1.6.6 you can configure your settings.json like so:
```jsonc
{
  "simpleTodo.overrideFoldersToIgnore": [
    "Library",
    "plugins",
    "mu-plugins",
    "vendor",
    "wp",
    "dev",
    "prod",
    "node_modules",
    "dist",
    "build",
    ".next"
  ]
}
```

Let me know if this solved your problem.

**Comment by rollecode** [comment]
Seems to work, thanks!
